### ISSUE TITLE
Command.simulate_query() loops infinitely if response_type is itertools.repeat

### ISSUE THREAD

**Issue by therealpyro** [p3trus/slave#159]
When the response_type of a query is itertools.repeat(...) the simulate_query function loops infinitely because of this line of code:

    response = [t.simulate() for t in self._query.response_type]

**Comment by p3trus** [comment]
Yeah I know. Was just too lazy to implement a check. Btw. see #140 at the end. I'm adding a Stream type in the near future. This will reduce the uglyness of the itertools types.
